version: '3'
services:
  eureka-service:
    build: ./DiscoveryService/
    hostname: discovery-service
    ports:
      - "8761:8761"
    networks:
      - default-network

  customer-service:
    build: ./CustomerService/
    hostname: customer-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-service
    environment:
      - eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka
    networks:
      - default-network

  billing-service:
    build: ./BillingService/
    hostname: billing-service
    ports:
      - "8083:8083"
    restart: on-failure
    depends_on:
      - customer-service
      - eureka-service
    environment:
      - eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka
    networks:
      - default-network

  gateway-service:
    build: ./GatewayService/
    hostname: gateway-service
    ports:
      - "8888:8888"
    depends_on:
      - customer-service
      - billing-service
      - eureka-service
    environment:
      - eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka
    networks:
      - default-network

networks:
  default-network:
    driver: bridge